### PR TITLE
Try hasher 256 on the metal in CI

### PR DESCRIPTION
**Pull request by ckormanyos**
The purpose of this PR is to try for a hasher 256-bit on a bare-metal qemu-emulated ARM(R) Cortex(R)-M4F controller.

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) I needed to add some stuff to array, add some of algorithm and disable IO-streaming.

I needed to find a way to fully disable exceptions/assertions on the metal in the configuration, so I did something like in math with `BOOST_CRYPT_NO_EXCEPTIONS`.

With assertions allowed:

grafik

With assertions expanding to nothing:

grafik

**Comment by ckormanyos** [comment]
It's not quite right yet with `try`/`catch` as I disabled these only where I needed to and via the somewhat false method of disabling I/O-streams. I think we need mechanisms that clearly disable:
* I/O-streams
* Exceptions and try/catch
* Assertions

But I did not finalize all of that (yet) in this PR. I'd need a bit of help for that all.

**Comment by ckormanyos** [comment]
This is intended to be a preliminary handling of #37.

**Comment by ckormanyos** [comment]
I'm going to go ahead and merge this, but we still have to clarify and finish:
* Optionally disable I/O streams (including files).
* Optionally disable exceptions and `try`/`catch`.
* Optionally disable run-time assertions.

**Comment by ckormanyos** [comment]
Final note: CI seems quite stable @mborland would you consider branch protection on merge to develop/master sensible?

**Comment by mborland** [comment]
> Final note: CI seems quite stable @mborland would you consider branch protection on merge to develop/master sensible?

I added some basic rules

**Pull request merged**
